In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [6]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [20]:
a = np.asarray(l)

In [8]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [15]:
c = np.asanyarray(b)
c

matrix([[1, 2, 3, 4]])

In [16]:
type(c)

numpy.matrix

In [21]:
 d = a

In [22]:
d

array([1, 2, 3, 4])

In [23]:
d[0]

1

In [24]:
d[0] = 100

In [25]:
d

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
e = np.copy(a)

In [28]:
e

array([100,   2,   3,   4])

In [29]:
e[0] = 101 

In [31]:
e


array([101,   2,   3,   4])

In [32]:
a

array([100,   2,   3,   4])

In [39]:
np.fromfunction(lambda i ,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [42]:
x = np.fromfunction(lambda i ,j : i*j,(3,3))
x

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [47]:
y = x.reshape(1,9)
y

array([[0., 0., 0., 0., 1., 2., 0., 2., 4.]])