In [90]:
import numpy as np

In [91]:
l = [1,2,3,4]

In [92]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [93]:
type(ar)

numpy.ndarray

In [94]:
a = np.asarray(l)

In [95]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [96]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [97]:
c = np.asanyarray(b)
c

matrix([[1, 2, 3, 4]])

In [98]:
np.array([[1, 2] ,[3, 4]])

array([[1, 2],
       [3, 4]])

In [99]:
type(c)

numpy.matrix

In [100]:
 d = a

In [101]:
d

array([1, 2, 3, 4])

In [102]:
d[0]

1

In [103]:
d[1] = 100

In [104]:
d

array([  1, 100,   3,   4])

In [105]:
a

array([  1, 100,   3,   4])

In [106]:
e = np.copy(a)

In [107]:
e

array([  1, 100,   3,   4])

In [108]:
e[0] = 101 

In [109]:
e


array([101, 100,   3,   4])

In [110]:
a

array([  1, 100,   3,   4])

In [111]:
np.fromfunction(lambda i ,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [112]:
x = np.fromfunction(lambda i ,j : i*j,(3,3))
x

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [113]:
x.flatten()

array([0., 0., 0., 0., 1., 2., 0., 2., 4.])

In [114]:
y = x.reshape(1,9)
y

array([[0., 0., 0., 0., 1., 2., 0., 2., 4.]])

In [115]:
iterable = (i*i for i in range(9))
iterable

<generator object <genexpr> at 0x0000016B5AC24EE0>

In [116]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64.])

In [117]:
np.fromstring('234 564',sep=' ')

array([234., 564.])

In [118]:
a.ndim

1

In [119]:
ar2 = np.array([[1234],[5476]])
ar2

array([[1234],
       [5476]])

In [120]:
ar2.ndim

2

In [121]:
ar2.size

2

In [122]:
ar2.shape

(2, 1)

In [123]:
ar2.dtype

dtype('int32')

In [124]:
type(ar2)

numpy.ndarray

In [125]:
ar22 = np.array([(1.,2,3,4),(5,4,7,6)])
ar2

array([[1234],
       [5476]])

In [126]:
ar22.dtype

dtype('float64')

In [127]:
np.arange(2.3,8.5,1)

array([2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3])

In [128]:
list(np.arange(2.3,8.5,1))

[2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3]

In [129]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [130]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [132]:
on = np.ones((2,4,5))
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [133]:
on.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [134]:
on.min()

1.0

In [135]:
on+5

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]])

In [136]:
np.empty((2,4))

array([[1., 2., 3., 4.],
       [5., 4., 7., 6.]])

In [137]:
np.empty((3,2))

array([[8.48798317e-314, 8.48798317e-314],
       [8.48798317e-314, 8.48798317e-314],
       [8.48798317e-314, 8.48798317e-314]])

In [138]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [139]:
np.logspace(2,4,base=10)

array([  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
         145.63484775,   159.98587196,   175.75106249,   193.06977289,
         212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
         308.88435965,   339.32217719,   372.75937203,   409.49150624,
         449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
         655.12855686,   719.685673  ,   790.60432109,   868.51137375,
         954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
        1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
        2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
        2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
        4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
        6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
        9102.98177992, 10000.        ])

In [140]:
arr = np.random.randn(3,4)

In [141]:
import pandas as pd 

In [142]:
pd.DataFrame(arr)

0         1         2         3
0 -1.726108 -0.028116  1.912828 -1.083858
1  0.549221 -0.528707 -0.278998  1.098991
2  0.518893 -0.488059  1.117270  1.062401

In [143]:
np.random.rand(3,4)

array([[0.22160989, 0.88012868, 0.32124268, 0.76081247],
       [0.54165564, 0.0348432 , 0.82396676, 0.77007211],
       [0.4229176 , 0.31952321, 0.76688342, 0.52759912]])

In [144]:
np.random.randint(3,100,(4,5))

array([[ 5, 24, 52, 19, 49],
       [31, 23, 97, 12, 84],
       [13, 88, 84, 58, 90],
       [22, 73, 59, 71, 13]])

In [145]:
pd.DataFrame(np.random.randint(3,100,(400,544))).to_csv('hii.csv')

In [146]:
ad = pd.read_csv('hii.csv')
ad

Unnamed: 0   0   1   2   3   4   5   6   7   8  ...  534  535  536  537  \
0             0  97  52  12  51  66  34  74  17  77  ...   56   76   13   88   
1             1  13  40  60  66  92  83  87   7  85  ...   11    3   49   83   
2             2  13  26  53  56  62   6   4   8   7  ...   40   31   88   96   
3             3  44  73  27  43  69  68  14  88  77  ...   18   40   47   41   
4             4  51   5  59  26  19  28   5  90  10  ...   22   60   98   30   
..          ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...   
395         395  26  76  55   4  99  75  91  72  13  ...   81   72   51   74   
396         396  80  86   4  56  13  84  75  89  15  ...   64   27   19   74   
397         397  46  68  95  23  42  52  14  42  17  ...   11   74   10   19   
398         398  45   3   4  15  26  98  67  69  97  ...   70   63   20   76   
399         399  92  45  59  49  52  76  62  34  58  ...    9   64   45   53   

     538  539  540  541  542  543  
0     13   59   59   69   99   89  
1     58   74   75   47   80   40  
2     27   49   36   83   38   94  
3     12   30   39   33   80   90  
4     82   71   25   28   42   14  
..   ...  ...  ...  ...  ...  ...  
395   84   61   70   96   17   18  
396   52   86   83    7   25   91  
397   42   80   59   80   38   71  
398   89   36   13   78    7   29  
399   19    9   57   80   65   67  

[400 rows x 545 columns]

In [147]:
arr.reshape(1,12)

array([[-1.72610831, -0.02811619,  1.91282756, -1.08385781,  0.54922146,
        -0.52870671, -0.2789985 ,  1.09899054,  0.51889264, -0.48805949,
         1.11726978,  1.06240097]])

In [148]:
arr.reshape(6,2)

array([[-1.72610831, -0.02811619],
       [ 1.91282756, -1.08385781],
       [ 0.54922146, -0.52870671],
       [-0.2789985 ,  1.09899054],
       [ 0.51889264, -0.48805949],
       [ 1.11726978,  1.06240097]])

In [195]:
arr1 =np.random.randint(10,100,(6,7))

In [152]:
arr1

array([[0.25821022, 0.22853691, 0.10188673, 0.25873077, 0.44740313,
        0.17115298, 0.14245805],
       [0.37089755, 0.47181674, 0.54655918, 0.41440518, 0.18016717,
        0.63025991, 0.51375846],
       [0.23392514, 0.02095462, 0.45861648, 0.14522403, 0.96442433,
        0.63693331, 0.65721219],
       [0.67319063, 0.27734094, 0.11223096, 0.96024898, 0.07108806,
        0.33756761, 0.70098467],
       [0.46059857, 0.80164068, 0.03627373, 0.64904399, 0.51067284,
        0.06099518, 0.85843301],
       [0.3888545 , 0.32651504, 0.71438858, 0.52362535, 0.42159299,
        0.26876275, 0.2011932 ]])

In [155]:
arr2 =np.random.randint(10,100,(6,7))

In [156]:
arr2

array([[33, 82, 43, 83, 97, 64, 10],
       [47, 67, 80, 34, 29, 97, 64],
       [89, 37, 43, 65, 44, 45, 84],
       [17, 90, 27, 73, 30, 33, 34],
       [37, 34, 81, 63, 35, 97, 54],
       [64, 51, 86, 14, 14, 54, 73]])

In [168]:
arr2[2,-1]

84

In [169]:
arr2[5,-4]

14

In [178]:
arr2[arr2>=50]

array([82, 83, 97, 64, 67, 80, 97, 64, 89, 65, 84, 90, 73, 81, 63, 97, 54,
       64, 51, 86, 54, 73])

In [179]:
arr2

array([[33, 82, 43, 83, 97, 64, 10],
       [47, 67, 80, 34, 29, 97, 64],
       [89, 37, 43, 65, 44, 45, 84],
       [17, 90, 27, 73, 30, 33, 34],
       [37, 34, 81, 63, 35, 97, 54],
       [64, 51, 86, 14, 14, 54, 73]])

In [192]:
arr2[2:3,-5:6]

array([[43, 65, 44, 45]])

In [193]:
arr2[0][1]=1000

In [194]:
arr2

array([[  33, 1000,   43,   83,   97,   64,   10],
       [  47,   67,   80,   34,   29,   97,   64],
       [  89,   37,   43,   65,   44,   45,   84],
       [  17,   90,   27,   73,   30,   33,   34],
       [  37,   34,   81,   63,   35,   97,   54],
       [  64,   51,   86,   14,   14,   54,   73]])

In [196]:
arr1+arr2

array([[  79, 1056,   69,  182,  182,   81,  100],
       [  80,  102,   92,   87,   94,  144,  123],
       [ 188,  111,   60,   81,   94,  141,  175],
       [  42,  119,  111,  135,  113,   54,  133],
       [  68,   51,  112,  156,  132,  153,   96],
       [ 154,   65,  114,   45,   24,   73,  132]])

In [200]:
arr3 =np.random.randint(1,9,(3,3))
arr4=np.random.randint(1,9,(3,3))

In [201]:
arr3

array([[7, 1, 2],
       [8, 2, 8],
       [3, 5, 2]])

In [202]:
arr4

array([[5, 1, 6],
       [2, 3, 5],
       [4, 3, 7]])

In [203]:
arr3-arr4

array([[ 2,  0, -4],
       [ 6, -1,  3],
       [-1,  2, -5]])

In [204]:
arr3+arr4


array([[12,  2,  8],
       [10,  5, 13],
       [ 7,  8,  9]])

In [205]:
arr3*arr4

array([[35,  1, 12],
       [16,  6, 40],
       [12, 15, 14]])

In [206]:
arr3/arr4

array([[1.4       , 1.        , 0.33333333],
       [4.        , 0.66666667, 1.6       ],
       [0.75      , 1.66666667, 0.28571429]])

In [211]:
arr3>=arr4

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [209]:
arr3

array([[7, 1, 2],
       [8, 2, 8],
       [3, 5, 2]])

In [210]:
arr4

array([[5, 1, 6],
       [2, 3, 5],
       [4, 3, 7]])

In [213]:
arr3@arr4

array([[51, 26, 77],
       [36, 26, 62],
       [54, 34, 88]])

matrix Broadcasting

In [221]:
v1 = np.zeros((3,4))
v1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [218]:
row = np.array([1,2,3,4])

In [220]:
v1 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [228]:
rows = np.array([[1,2,3]])

In [229]:
rows.T + v1

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [231]:
np.sqrt(arr4)

array([[2.23606798, 1.        , 2.44948974],
       [1.41421356, 1.73205081, 2.23606798],
       [2.        , 1.73205081, 2.64575131]])

In [232]:
np.exp(arr4)

array([[ 148.4131591 ,    2.71828183,  403.42879349],
       [   7.3890561 ,   20.08553692,  148.4131591 ],
       [  54.59815003,   20.08553692, 1096.63315843]])

In [234]:
np.log10(arr4)

array([[0.69897   , 0.        , 0.77815125],
       [0.30103   , 0.47712125, 0.69897   ],
       [0.60205999, 0.47712125, 0.84509804]])