In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [4]:
type(ar)

numpy.ndarray

In [5]:
a = np.asarray(l)

In [6]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [7]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [8]:
c = np.asanyarray(b)
c

matrix([[1, 2, 3, 4]])

In [9]:
np.array([[1, 2] ,[3, 4]])

array([[1, 2],
       [3, 4]])

In [10]:
type(c)

numpy.matrix

In [11]:
 d = a

In [12]:
d

array([1, 2, 3, 4])

In [13]:
d[0]

1

In [14]:
d[0] = 100

In [15]:
d

array([100,   2,   3,   4])

In [16]:
a

array([100,   2,   3,   4])

In [17]:
e = np.copy(a)

In [18]:
e

array([100,   2,   3,   4])

In [19]:
e[0] = 101 

In [20]:
e


array([101,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
np.fromfunction(lambda i ,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
x = np.fromfunction(lambda i ,j : i*j,(3,3))
x

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
y = x.reshape(1,9)
y

array([[0., 0., 0., 0., 1., 2., 0., 2., 4.]])

In [25]:
iterable = (i*i for i in range(9))
iterable

<generator object <genexpr> at 0x0000016B58745B10>

In [26]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64.])

In [27]:
np.fromstring('234 564',sep=' ')

array([234., 564.])

In [28]:
a.ndim

1

In [29]:
ar2 = np.array([[1234],[5476]])
ar2

array([[1234],
       [5476]])

In [30]:
ar2.ndim

2

In [31]:
ar2.size

2

In [32]:
ar2.shape

(2, 1)

In [33]:
ar2.dtype

dtype('int32')

In [34]:
type(ar2)

numpy.ndarray

In [35]:
ar22 = np.array([(1.,2,3,4),(5,4,7,6)])
ar2

array([[1234],
       [5476]])

In [36]:
ar22.dtype

dtype('float64')

In [37]:
np.arange(2.3,8.5,1)

array([2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3])

In [38]:
list(np.arange(2.3,8.5,1))

[2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3]

In [39]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [40]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
on = np.ones((2,4,5))
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [43]:
on+5

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]])

In [44]:
np.empty((2,4))

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]])

In [45]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [47]:
np.logspace(2,4,base=10)

array([  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
         145.63484775,   159.98587196,   175.75106249,   193.06977289,
         212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
         308.88435965,   339.32217719,   372.75937203,   409.49150624,
         449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
         655.12855686,   719.685673  ,   790.60432109,   868.51137375,
         954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
        1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
        2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
        2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
        4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
        6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
        9102.98177992, 10000.        ])

In [48]:
arr = np.random.randn(3,4)

In [49]:
import pandas as pd 

In [50]:
pd.DataFrame(arr)

0         1         2         3
0  0.682260  1.780952 -0.125604 -1.569234
1 -1.845758  1.584198  0.685954  1.978004
2  1.216446 -1.215675 -1.193343 -0.180113

In [51]:
np.random.rand(3,4)

array([[0.72322905, 0.78679466, 0.10061553, 0.18071787],
       [0.94895955, 0.07719033, 0.97329192, 0.00741267],
       [0.2139003 , 0.42565362, 0.36018649, 0.03427115]])

In [52]:
np.random.randint(3,100,(4,5))

array([[31, 94,  3, 52, 73],
       [24, 26, 16, 97,  9],
       [18, 18, 51, 80, 81],
       [16, 40, 83, 68, 93]])

In [53]:
pd.DataFrame(np.random.randint(3,100,(400,544))).to_csv('hii.csv')

In [54]:
ad = pd.read_csv('hii.csv')
ad

Unnamed: 0   0   1   2   3   4   5   6   7   8  ...  534  535  536  537  \
0             0  57  71  77  73  83  98   9   9  46  ...   57   89   19   44   
1             1   6  39  62  22  88  56  75  34  15  ...   92   40    8   41   
2             2  15  53  79  46  86  65  58  83  43  ...    4   32   77   60   
3             3  74  94  74  40  65  64   9  82  87  ...   58   82   71   39   
4             4  68  84  68  13  43  62  83  25  41  ...   70   54   19    6   
..          ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...   
395         395   3  45  97  63  96  80  76  64  47  ...   92   80   30   96   
396         396   7  94  29  63  59  90   5  30   8  ...   17   72   69   52   
397         397  96  67  14  92  97   6  16  43  32  ...   97   69   45    7   
398         398  53  30  55  28  15  13   7  64  82  ...    3    8   43   51   
399         399   8  93  85  93  64  19  80   5  51  ...   52   84   69   21   

     538  539  540  541  542  543  
0     54   59    5   59   32   77  
1     47   93   96   10   86   84  
2     53   76   68   48   70   67  
3     41   54   13   53   95   40  
4     22    9   99    7   48   36  
..   ...  ...  ...  ...  ...  ...  
395   91   46   49   57   95   34  
396   88   71    6   53    6   83  
397   51   33   74   86   77   44  
398   95   22   69   62   88   46  
399   38    3   68   35   58   11  

[400 rows x 545 columns]

In [55]:
arr.reshape(1,12)

array([[ 0.68226046,  1.78095239, -0.12560448, -1.56923393, -1.84575779,
         1.58419816,  0.68595366,  1.97800424,  1.21644632, -1.2156748 ,
        -1.19334321, -0.18011347]])