In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
a = np.asarray(l)

In [7]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [8]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [9]:
c = np.asanyarray(b)
c

matrix([[1, 2, 3, 4]])

In [26]:
np.array([[1, 2] ,[3, 4]])

array([[1, 2],
       [3, 4]])

In [11]:
type(c)

numpy.matrix

In [12]:
 d = a

In [13]:
d

array([1, 2, 3, 4])

In [14]:
d[0]

1

In [15]:
d[0] = 100

In [16]:
d

array([100,   2,   3,   4])

In [17]:
a

array([100,   2,   3,   4])

In [18]:
e = np.copy(a)

In [19]:
e

array([100,   2,   3,   4])

In [20]:
e[0] = 101 

In [21]:
e


array([101,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
np.fromfunction(lambda i ,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
x = np.fromfunction(lambda i ,j : i*j,(3,3))
x

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [25]:
y = x.reshape(1,9)
y

array([[0., 0., 0., 0., 1., 2., 0., 2., 4.]])

In [34]:
iterable = (i*i for i in range(9))
iterable

<generator object <genexpr> at 0x0000025B7F28EC20>

In [35]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64.])

In [39]:
np.fromstring('234 564',sep=' ')

array([234., 564.])

In [44]:
a.ndim

1

In [46]:
ar2 = np.array([[1234],[5476]])
ar2

array([[1234],
       [5476]])

In [47]:
ar2.ndim

2

In [48]:
ar2.size

2

In [54]:
ar2.shape

(2, 1)

In [53]:
ar2.dtype

dtype('int32')

In [55]:
type(ar2)

numpy.ndarray

In [60]:
ar22 = np.array([(1.,2,3,4),(5,4,7,6)])
ar2

array([[1234],
       [5476]])

In [61]:
ar22.dtype

dtype('float64')

In [63]:
np.arange(2.3,8.5,1)

array([2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3])

In [65]:
list(np.arange(2.3,8.5,1))

[2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3]

In [82]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [83]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [103]:
on = np.ones((2,4,5))
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [106]:
on+5

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]])

In [111]:
np.empty((2,4))

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]])

In [113]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [119]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [127]:
np.logspace(2,4,base=10)

array([  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
         145.63484775,   159.98587196,   175.75106249,   193.06977289,
         212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
         308.88435965,   339.32217719,   372.75937203,   409.49150624,
         449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
         655.12855686,   719.685673  ,   790.60432109,   868.51137375,
         954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
        1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
        2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
        2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
        4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
        6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
        9102.98177992, 10000.        ])

In [131]:
arr = np.random.randn(3,4)

In [132]:
import pandas as pd 

In [135]:
pd.DataFrame(arr)

0         1         2         3
0  0.091858 -1.158582  0.013309 -0.396981
1 -1.384025  0.039820  1.144486  0.007150
2  0.994514  0.353418 -0.391364 -1.063138

In [136]:
np.random.rand(3,4)

array([[0.11389179, 0.40919162, 0.27605568, 0.72368407],
       [0.86369092, 0.32387931, 0.20340554, 0.23645063],
       [0.18706167, 0.22078042, 0.64969087, 0.89482222]])

In [143]:
np.random.randint(3,100,(4,5))

array([[28,  6, 31, 44, 92],
       [10, 34, 63, 38, 61],
       [19, 89,  4, 70,  7],
       [15, 87, 75, 75, 93]])

In [148]:
pd.DataFrame(np.random.randint(3,100,(400,544))).to_csv('hii.csv')

In [149]:
ad = pd.read_csv('hii.csv')
ad

Unnamed: 0   0   1   2   3   4   5   6   7   8  ...  534  535  536  537  \
0             0  78  25  95  33  43  95   4  44  19  ...   10   58   58    8   
1             1  18  34  15  33  81  60  97  79  62  ...    9   43   19   41   
2             2   4  55  75  68  43  21  19  43  78  ...   53   91   54   56   
3             3  90  50  84  30  75  11  95  66  10  ...   76   74   91   69   
4             4   9  32  76   8  12  28  71  72  10  ...   43   93   61   82   
..          ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...   
395         395  51  18  94  21  17  73  48  48  71  ...   75   27   81   45   
396         396  68  32  79  84  33  65  66  93  89  ...   15   52   38   92   
397         397  21  46  63   6  97  27  80  94  81  ...   95   51   14   74   
398         398  36  64  33  56  48  98  84  29  34  ...   51   43   28   95   
399         399   9  99  81  24  21  37  51  96  67  ...   46   87   37   99   

     538  539  540  541  542  543  
0     43   74   39   90   48   59  
1     40   86   18   23   42   13  
2     61   23   14   27   14   14  
3     21   77   26   31    9   78  
4     21   14   69   27    9   76  
..   ...  ...  ...  ...  ...  ...  
395    8   79   79   71   47   98  
396   82   67   41   51   42   46  
397   84   27   57   12   93   39  
398   20   50    6   96   38   51  
399   81   82   93   24   13   31  

[400 rows x 545 columns]

In [156]:
arr.reshape(1,12)

array([[ 0.09185809, -1.15858236,  0.01330943, -0.39698144, -1.38402462,
         0.03982038,  1.1444859 ,  0.00715036,  0.99451383,  0.35341756,
        -0.39136379, -1.06313847]])