In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [4]:
type(ar)

numpy.ndarray

In [5]:
a = np.asarray(l)

In [6]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [7]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [8]:
c = np.asanyarray(b)
c

matrix([[1, 2, 3, 4]])

In [9]:
np.array([[1, 2] ,[3, 4]])

array([[1, 2],
       [3, 4]])

In [10]:
type(c)

numpy.matrix

In [11]:
 d = a

In [12]:
d

array([1, 2, 3, 4])

In [13]:
d[0]

1

In [14]:
d[1] = 100

In [15]:
d

array([  1, 100,   3,   4])

In [16]:
a

array([  1, 100,   3,   4])

In [17]:
e = np.copy(a)

In [18]:
e

array([  1, 100,   3,   4])

In [19]:
e[0] = 101 

In [20]:
e


array([101, 100,   3,   4])

In [21]:
a

array([  1, 100,   3,   4])

In [22]:
np.fromfunction(lambda i ,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
x = np.fromfunction(lambda i ,j : i*j,(3,3))
x

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
x.flatten()

array([0., 0., 0., 0., 1., 2., 0., 2., 4.])

In [25]:
y = x.reshape(1,9)
y

array([[0., 0., 0., 0., 1., 2., 0., 2., 4.]])

In [26]:
iterable = (i*i for i in range(9))
iterable

<generator object <genexpr> at 0x00000284AC2F2740>

In [27]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64.])

In [28]:
np.fromstring('234 564',sep=' ')

array([234., 564.])

In [29]:
a.ndim

1

In [30]:
ar2 = np.array([[1234],[5476]])
ar2

array([[1234],
       [5476]])

In [31]:
ar2.ndim

2

In [32]:
ar2.size

2

In [33]:
ar2.shape

(2, 1)

In [34]:
ar2.dtype

dtype('int32')

In [35]:
type(ar2)

numpy.ndarray

In [36]:
ar22 = np.array([(1.,2,3,4),(5,4,7,6)])
ar2

array([[1234],
       [5476]])

In [37]:
ar22.dtype

dtype('float64')

In [38]:
np.arange(2.3,8.5,1)

array([2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3])

In [39]:
list(np.arange(2.3,8.5,1))

[2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3]

In [40]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [41]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
on = np.ones((2,4,5))
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [44]:
on.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [45]:
on.min()

1.0

In [46]:
on+5

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]])

In [47]:
np.empty((2,4))

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]])

In [48]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [50]:
np.logspace(2,4,base=10)

array([  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
         145.63484775,   159.98587196,   175.75106249,   193.06977289,
         212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
         308.88435965,   339.32217719,   372.75937203,   409.49150624,
         449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
         655.12855686,   719.685673  ,   790.60432109,   868.51137375,
         954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
        1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
        2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
        2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
        4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
        6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
        9102.98177992, 10000.        ])

In [51]:
arr = np.random.randn(3,4)

In [52]:
import pandas as pd 

In [53]:
pd.DataFrame(arr)

0         1         2         3
0  0.647147  0.525095 -1.037180 -0.606316
1  0.809496  0.825609  0.001873  0.381994
2 -0.535515 -0.614629  1.189144 -0.996385

In [54]:
np.random.rand(3,4)

array([[0.71509864, 0.63212041, 0.43574941, 0.32668047],
       [0.26488144, 0.33655338, 0.12341975, 0.54083028],
       [0.61278568, 0.41267641, 0.77123947, 0.99308434]])

In [55]:
np.random.randint(3,100,(4,5))

array([[47, 17, 49, 62, 81],
       [88, 71, 65, 80, 58],
       [96, 75, 18, 27, 17],
       [52, 92, 26, 54, 17]])

In [56]:
pd.DataFrame(np.random.randint(3,100,(400,544))).to_csv('hii.csv')

In [57]:
ad = pd.read_csv('hii.csv')
ad

Unnamed: 0   0   1   2   3   4   5   6   7   8  ...  534  535  536  537  \
0             0  58  61  44  20   6  88  14  70  35  ...   66   41   50   99   
1             1  23   5   5  15  57  39  33  80  92  ...   42   49   70   44   
2             2  56  17  53  25   6  77  41  17  70  ...   73   64   31   78   
3             3  72  28   4  41  41  61  29  86  36  ...   54    4   25   44   
4             4  61  77  98  87  60  77  26  36  55  ...   28   57   27   96   
..          ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...   
395         395  73  43  90  67  94   4  34  37   6  ...   76   51   82    4   
396         396  16  58  48  75  17  75  24  47  99  ...   30   10   82   59   
397         397  61  13  59  50  13  87  70  69  85  ...   69   81   34   84   
398         398  21  55  19  17  67  86  64  83  20  ...   95   15   44   67   
399         399  25  15  28  64  39  62  23  79  54  ...    3   41   94   62   

     538  539  540  541  542  543  
0     93   29   87   63   40   97  
1     12   15   86    4   96   64  
2     16   22   39   73   11   78  
3     46   73    7   59   72    8  
4     84   28   31   21   49   48  
..   ...  ...  ...  ...  ...  ...  
395   19    7   24   97   57   55  
396   22   70   18   15    7   67  
397   67   45   73   70   36   91  
398   60   69   78   59   77   82  
399   72   72   56   10   94   14  

[400 rows x 545 columns]

In [58]:
arr.reshape(1,12)

array([[ 0.64714735,  0.52509547, -1.03717969, -0.60631638,  0.80949613,
         0.82560926,  0.00187252,  0.38199404, -0.53551501, -0.61462861,
         1.18914425, -0.99638513]])

In [59]:
arr.reshape(6,2)

array([[ 0.64714735,  0.52509547],
       [-1.03717969, -0.60631638],
       [ 0.80949613,  0.82560926],
       [ 0.00187252,  0.38199404],
       [-0.53551501, -0.61462861],
       [ 1.18914425, -0.99638513]])

In [60]:
arr1 =np.random.randint(10,100,(6,7))

In [61]:
arr1

array([[76, 49, 70, 45, 98, 89, 41],
       [98, 34, 35, 96, 52, 64, 80],
       [17, 51, 82, 17, 46, 91, 71],
       [81, 80, 68, 62, 34, 99, 20],
       [20, 61, 81, 14, 90, 52, 64],
       [85, 94, 22, 51, 15, 34, 76]])

In [62]:
arr2 =np.random.randint(10,100,(6,7))

In [63]:
arr2

array([[50, 57, 41, 90, 71, 51, 28],
       [94, 77, 42, 59, 49, 34, 50],
       [71, 87, 15, 92, 71, 53, 69],
       [96, 62, 17, 72, 75, 88, 83],
       [79, 27, 57, 36, 86, 94, 16],
       [48, 84, 52, 80, 44, 19, 48]])

In [64]:
arr2[2,-1]

69

In [65]:
arr2[5,-4]

80

In [66]:
arr2[arr2>=50]

array([50, 57, 90, 71, 51, 94, 77, 59, 50, 71, 87, 92, 71, 53, 69, 96, 62,
       72, 75, 88, 83, 79, 57, 86, 94, 84, 52, 80])

In [67]:
arr2

array([[50, 57, 41, 90, 71, 51, 28],
       [94, 77, 42, 59, 49, 34, 50],
       [71, 87, 15, 92, 71, 53, 69],
       [96, 62, 17, 72, 75, 88, 83],
       [79, 27, 57, 36, 86, 94, 16],
       [48, 84, 52, 80, 44, 19, 48]])

In [95]:
hii = arr2.flatten()

In [68]:
arr2[2:3,-5:6]

array([[15, 92, 71, 53]])

In [69]:
arr2[0][1]=1000

In [70]:
arr2

array([[  50, 1000,   41,   90,   71,   51,   28],
       [  94,   77,   42,   59,   49,   34,   50],
       [  71,   87,   15,   92,   71,   53,   69],
       [  96,   62,   17,   72,   75,   88,   83],
       [  79,   27,   57,   36,   86,   94,   16],
       [  48,   84,   52,   80,   44,   19,   48]])

In [71]:
arr1+arr2

array([[ 126, 1049,  111,  135,  169,  140,   69],
       [ 192,  111,   77,  155,  101,   98,  130],
       [  88,  138,   97,  109,  117,  144,  140],
       [ 177,  142,   85,  134,  109,  187,  103],
       [  99,   88,  138,   50,  176,  146,   80],
       [ 133,  178,   74,  131,   59,   53,  124]])

In [72]:
arr3 =np.random.randint(1,9,(3,3))
arr4=np.random.randint(1,9,(3,3))

In [73]:
arr3

array([[2, 7, 8],
       [4, 6, 5],
       [3, 6, 3]])

In [74]:
arr4

array([[2, 7, 5],
       [2, 3, 7],
       [3, 3, 7]])

In [75]:
arr3-arr4

array([[ 0,  0,  3],
       [ 2,  3, -2],
       [ 0,  3, -4]])

In [76]:
arr3+arr4


array([[ 4, 14, 13],
       [ 6,  9, 12],
       [ 6,  9, 10]])

In [77]:
arr3*arr4

array([[ 4, 49, 40],
       [ 8, 18, 35],
       [ 9, 18, 21]])

In [78]:
arr3/arr4

array([[1.        , 1.        , 1.6       ],
       [2.        , 2.        , 0.71428571],
       [1.        , 2.        , 0.42857143]])

In [79]:
arr3>=arr4

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [80]:
arr3

array([[2, 7, 8],
       [4, 6, 5],
       [3, 6, 3]])

In [81]:
arr4

array([[2, 7, 5],
       [2, 3, 7],
       [3, 3, 7]])

In [82]:
arr3@arr4

array([[ 42,  59, 115],
       [ 35,  61,  97],
       [ 27,  48,  78]])

matrix Broadcasting

In [83]:
v1 = np.zeros((3,4))
v1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
row = np.array([1,2,3,4])

In [85]:
v1 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [86]:
rows = np.array([[1,2,3]])

In [87]:
rows.T + v1

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [88]:
np.sqrt(arr4)

array([[1.41421356, 2.64575131, 2.23606798],
       [1.41421356, 1.73205081, 2.64575131],
       [1.73205081, 1.73205081, 2.64575131]])

In [89]:
np.exp(arr4)

array([[   7.3890561 , 1096.63315843,  148.4131591 ],
       [   7.3890561 ,   20.08553692, 1096.63315843],
       [  20.08553692,   20.08553692, 1096.63315843]])

In [90]:
np.log10(arr4)

array([[0.30103   , 0.84509804, 0.69897   ],
       [0.30103   , 0.47712125, 0.84509804],
       [0.47712125, 0.47712125, 0.84509804]])

In [92]:
np.sort(arr2)

array([[  28,   41,   50,   51,   71,   90, 1000],
       [  34,   42,   49,   50,   59,   77,   94],
       [  15,   53,   69,   71,   71,   87,   92],
       [  17,   62,   72,   75,   83,   88,   96],
       [  16,   27,   36,   57,   79,   86,   94],
       [  19,   44,   48,   48,   52,   80,   84]])

In [109]:
np.sort(hii)

array([  15,   16,   17,   19,   27,   28,   34,   36,   41,   42,   44,
         48,   48,   49,   50,   50,   51,   52,   53,   57,   59,   62,
         69,   71,   71,   71,   72,   75,   77,   79,   80,   83,   84,
         86,   87,   88,   90,   92,   94,   94,   96, 1000])

In [110]:
np.searchsorted(hii,96)

21

In [108]:
np.count_nonzero(hii)

42

In [114]:
np.where(hii>20)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17,
        18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36,
        37, 38, 39, 41], dtype=int64),)

In [120]:
np.extract(arr3>3,arr4)

array([7, 5, 2, 3, 7, 3])

In [117]:
arr3

array([[2, 7, 8],
       [4, 6, 5],
       [3, 6, 3]])

In [118]:
arr4

array([[2, 7, 5],
       [2, 3, 7],
       [3, 3, 7]])

In [121]:
hii

array([  50, 1000,   41,   90,   71,   51,   28,   94,   77,   42,   59,
         49,   34,   50,   71,   87,   15,   92,   71,   53,   69,   96,
         62,   17,   72,   75,   88,   83,   79,   27,   57,   36,   86,
         94,   16,   48,   84,   52,   80,   44,   19,   48])

In [122]:
hii.byteswap()

array([ 838860800, -402456576,  687865856, 1509949440, 1191182336,
        855638016,  469762048, 1577058304, 1291845632,  704643072,
        989855744,  822083584,  570425344,  838860800, 1191182336,
       1459617792,  251658240, 1543503872, 1191182336,  889192448,
       1157627904, 1610612736, 1040187392,  285212672, 1207959552,
       1258291200, 1476395008, 1392508928, 1325400064,  452984832,
        956301312,  603979776, 1442840576, 1577058304,  268435456,
        805306368, 1409286144,  872415232, 1342177280,  738197504,
        318767104,  805306368])

Deep copy

In [123]:
a= np.copy(hii)

In [124]:
a

array([  50, 1000,   41,   90,   71,   51,   28,   94,   77,   42,   59,
         49,   34,   50,   71,   87,   15,   92,   71,   53,   69,   96,
         62,   17,   72,   75,   88,   83,   79,   27,   57,   36,   86,
         94,   16,   48,   84,   52,   80,   44,   19,   48])

In [126]:
b = a.view()
b

array([  50, 1000,   41,   90,   71,   51,   28,   94,   77,   42,   59,
         49,   34,   50,   71,   87,   15,   92,   71,   53,   69,   96,
         62,   17,   72,   75,   88,   83,   79,   27,   57,   36,   86,
         94,   16,   48,   84,   52,   80,   44,   19,   48])

In [130]:
b[0]=200

In [133]:
a

array([ 200, 1000,   41,   90,   71,   51,   28,   94,   77,   42,   59,
         49,   34,   50,   71,   87,   15,   92,   71,   53,   69,   96,
         62,   17,   72,   75,   88,   83,   79,   27,   57,   36,   86,
         94,   16,   48,   84,   52,   80,   44,   19,   48])

In [134]:
b

array([ 200, 1000,   41,   90,   71,   51,   28,   94,   77,   42,   59,
         49,   34,   50,   71,   87,   15,   92,   71,   53,   69,   96,
         62,   17,   72,   75,   88,   83,   79,   27,   57,   36,   86,
         94,   16,   48,   84,   52,   80,   44,   19,   48])

In [135]:
z = [1,2,3,4,5,0,8,5,2,6,4,7]

In [ ]:
arrz = np

In [136]:
import numpy.matlib as nm

In [139]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])